name: check failed bizid

on:
  workflow_dispatch:
  page_build:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16

      - name: Get dependencies
        run: |
          go get -v -t -d ./...

      - name: Run
        id: check
        run: |
          go run ./check-failed-biz
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
